### ISSUE TITLE
Sona maker

### ISSUE THREAD

**Issue by ghost** [bunfan/beat-banger#113]
Assuming this has been something already thought about but I’d think it be cool to lets us put our characters in the game.

**Comment by Lumpian** [comment]
jera except he is canonically the final boss of bunbanger (200 bpm, failed orgasm notes, visual gimmick hell)

**Comment by theGrames** [comment]
We aren't looking into a sona maker, per say, but we are going to try and have character customization and attire choices, for both you and the various NPC's.
