### ISSUE TITLE
This is less of a bug and more of an outdated chart. This issue resides because of the implementation of `last_transition`. `cum_fx` are only broken on charts that lack `last_transiton` and instead have a final normal transition.

### ISSUE THREAD

**Issue by Rippl2** [bunfan/beat-banger#116]
This is less of a bug and more of an outdated chart. This issue resides because of the implementation of `last_transition`. `cum_fx` are only broken on charts that lack `last_transiton` and instead have a final normal transition.

_Originally posted by @theGrames in https://github.com/bunfan/beat-banger-public/issues/76#issuecomment-972593292_

**Comment by theGrames** [comment]
ok
