### ISSUE TITLE
Photosensitivity Accesibility Options (i.e: Disable Screen Flashing)

### ISSUE THREAD

**Issue by monochromia** [bunfan/beat-banger#117]
**What feature would you like to request?:**
A toggleable option in the menu that turns off the white screenflash effect.

**Comment by theGrames** [comment]
Screenflash can already be turned off in 1.3 on a per-stage basis, found [here](https://github.com/bunfan/beat-banger/wiki/Chart-Formatting-1.3#parameters) under **Other**.
