### ISSUE TITLE
Mega's mods download got cancelled 

### ISSUE THREAD

**Issue by KizunaTamashi** [bunfan/beat-banger#121]
**Describe the bug**
When you go to Mega.nz's Mods folder you get that "this link is unavailable as the user’s account has been closed for gross violation of mega" making impossible downloading Mods

**To Reproduce**
1. Go to 'https://mega.nz/folder/Vk0CVSIQ#KHCffROl-7_3d71QxBNoTQ'
2. Wait it to load
3. And here is the error

**Expected behavior**
Loading into the folders with the possibility of downloading them

**Screenshots**
![Screenshot (1194)](https://user-images.githubusercontent.com/97866102/149707914-02764a60-2245-4518-a379-0b28fc3fb9e3.png)

**Comment by theGrames** [comment]
Not a bug, the fan-managed cloud storage was taken down because of TOS about adult content. It is unrecoverable. I am looking into alternatives.
